<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hlpngserialisation"
    nsURI="http://org.pnml.tools/epnk/pntypes/hlpng/serialisation" nsPrefix="hlpngserialisation">
  <eClassifiers xsi:type="ecore:EClass" name="SortAssoc" eSuperTypes="../../org.pnml.tools.epnk/model/Serialisation.ecore#//AssocClass ../../org.pnml.tools.epnk.pntypes.hlpngs.datatypes/model/HLPNGDataTypes.ecore#//terms/Sort"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclAssoc" eSuperTypes="../../org.pnml.tools.epnk/model/Serialisation.ecore#//AssocClass ../../org.pnml.tools.epnk.pntypes.hlpngs.datatypes/model/HLPNGDataTypes.ecore#//terms/Declarations"/>
  <eClassifiers xsi:type="ecore:EClass" name="TermAssoc" eSuperTypes="../../org.pnml.tools.epnk/model/Serialisation.ecore#//AssocClass ../../org.pnml.tools.epnk.pntypes.hlpngs.datatypes/model/HLPNGDataTypes.ecore#//terms/Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclAssoc" eSuperTypes="../../org.pnml.tools.epnk/model/Serialisation.ecore#//AssocClass ../../org.pnml.tools.epnk.pntypes.hlpngs.datatypes/model/HLPNGDataTypes.ecore#//terms/VariableDecl"/>
</ecore:EPackage>
